### ISSUE TITLE
headless characters when exiting in head-zoomed-camera position

### ISSUE THREAD

**Issue by fly-77** [Outerra/anteworld#11]
Characters loose their head when they are exited while the camera is  zoomed into the head)

**Comment by cameni** [comment]
Just tried it, exited from character while it was zoomed in, but it still has head attached.

**Comment by fly-77** [comment]
which one ? for the assembled one OK head remains attached because it actually doesn't zoom into the head but "above the head" but for the swat the head gets cut.

**Comment by cameni** [comment]
Well, you wrote "characters" :)
But you were right, the assembled one only doesn't lose head because it's not configured properly.
